### ISSUE TITLE
Error: Unsupported Service. Please check if you have the latest version of the app

### ISSUE THREAD

**Issue by duckybrpy** [xXxCLOTIxXx/projectZ.py#1]
File "/root/Documents/ProjZBot/script.py", line 34, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/Documents/ProjZBot/script.py", line 28, in main
    await client.login(email=*, password=*)
  File "/usr/local/lib/python3.9/dist-packages/projectZ/async_client.py", line 86, in login
    if response.status != 200: return exceptions.CheckException(await response.text())
  File "/usr/local/lib/python3.9/dist-packages/projectZ/utils/exceptions.py", line 80, in CheckException
    else:raise UnknownError(data)
projectZ.utils.exceptions.UnknownError: {'apiCode': 4, 'apiMsg': 'Unsupported Service. Please check if you have the latest version of the app.'}

**Comment by THE-EXP** [comment]
Same with the synchronous version (Windows 10, module version: 1.1.6.8)
Traceback (most recent call last):
  File "c:\F\GitHub Repos\ProjZ-BotAcc\bot.py", line 4, in <module>
    client.login(email="dotseriesfeedback@gmail.com", password="kokoroiT17!")
  File "C:\Users\theex\AppData\Roaming\Python\Python311\site-packages\projectZ\client.py", line 64, in login
    if response.status_code != 200:return exceptions.CheckException(response.text)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theex\AppData\Roaming\Python\Python311\site-packages\projectZ\utils\exceptions.py", line 80, in CheckException
    else:raise UnknownError(data)
         ^^^^^^^^^^^^^^^^^^^^^^^^
projectZ.utils.exceptions.UnknownError: {'apiCode': 4, 'apiMsg': 'Unsupported Service. Please check if you have the latest version of the app.'}

**Comment by xXxCLOTIxXx** [comment]
The problem has already been resolved in the dev branch. As soon as I finish committing the async version, I’ll post it on pypi
